# -*- coding: utf-8 -*-
"""Lab10_Problem1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2QAMSQ4cGjrqTvkOg4GRObYJ24gq0BI

1.Dice probability
"""

import numpy as np

def roll_dice(prob=None):
    if not prob:
        return np.random.choice(a=[1,2,3,4,5,6])
    else:
        return np.random.choice(a=[1,2,3,4,5,6],p=prob)
           
def simulate(n=100,prob=None):
    reached=0
    for _ in range(n):
        throws=250
        curr_pos=0
        while throws:
            throws-=1
            curr_step=roll_dice(prob)
            if curr_pos>60:
                reached+=1
                break
                
            if curr_step in {1,2}:
                curr_pos-=1
            elif curr_step in {3,4,5}:
                curr_pos+=1
            else:
                curr_step=roll_dice(prob)
                curr_pos+=curr_step
    print(reached/n)
simulate() 
simulate(prob=[0.2,0.3,0.2,0.1,0.1,0.1])

simulate(1000)
simulate(1000,[0.2,0.3,0.2,0.1,0.1,0.1])